# Generated by Django 2.2.13 on 2020-07-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_citizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('supply_time', models.IntegerField(choices=[(0, 'Less than 6 Hours per week'), (1, 'More than 6 hours but less than 24 hours this week'), (2, 'More than 24 hours this week')])),
                ('tanker', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('comment', models.CharField(blank=True, max_length=240)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citizen.Citizen')),
            ],
        ),
    ]
