# Generated by Django 2.2.13 on 2020-07-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.Citizen'),
        ),
    ]
