# Generated by Django 2.2.13 on 2020-07-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0006_auto_20200723_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
